// Simplified Chinese message catalog for ClientSetupGuide. Keys are stable message IDs and
// match snippets/client-setup-labels-en.jsx. Placeholders keep their names.
export const clientSetupLabelsZhHans = {
  appsTitle: '先下载应用。',
  stepsTitle: '按步骤连接。',
  helpTitle: '卡住了？',
  nextTitle: '接下来做什么。',
  opensInNewTab: '（在新标签页中打开）',
  verifyRequired: '请在你亲自检查后，勾选每一项。',
  allDone: '所有步骤在此浏览器中都已标记为完成。',
  remainingSteps: '{count} 个步骤中有 {done} 个已标记为完成。请打开其他标签页完成剩余步骤。',
  progressReset: '你在此浏览器中的进度已重置。',
  vendorScreenshotTag: '厂商截图',
  kombifyScreenshotTag: 'KOMBIFY 截图',
  openVendorPage: '打开厂商页面',
  openScreenshot: '打开截图',
  vendorImageUnavailable: '加载需要网络连接。',
  imageUnavailable: '图片未能加载。',
  enlargeScreenshot: '放大截图：{description}',
  captured: '截取于 {date}',
  vendorGuideTag: '厂商指南',
  printGuide: '打印指南',
  requirementsTitle: '你需要准备什么',
  officialApp: '官方 · {vendor}',
  thirdPartyApp: '第三方 · {vendor}',
  setupSteps: '设置步骤',
  stepPosition: '第 {current} 步 / 共 {count} 步',
  progress: '{count} 个步骤中已完成 {done} 个',
  back: '返回',
  finish: '完成',
  next: '已完成 · 下一步',
  imageSources: '图片来源与日期',
  resetProgress: '重置进度',
  sourcesTitle: '图片来源、已核对的链接和日期',
  ownershipNotice: '由 kombify 提供的指南 · 产品名称、厂商应用截图和商标归其各自所有者所有。',
  vendorScreenshot: '厂商截图',
  screenshot: '截图',
  closeImage: '关闭图片',
  openOriginal: '在厂商处打开原图',
  aboutScreenshot: '关于此截图',
};
