// Spanish message catalog for ClientSetupGuide. Keys are stable message IDs and
// match snippets/client-setup-labels-en.jsx. Placeholders keep their names.
export const clientSetupLabelsEs = {
  appsTitle: 'Primero, descarga la app.',
  stepsTitle: 'Conéctate paso a paso.',
  helpTitle: '¿Te has atascado?',
  nextTitle: 'Qué viene después.',
  opensInNewTab: ' (se abre en una pestaña nueva)',
  verifyRequired: 'Marca cada punto después de comprobarlo por tu cuenta.',
  allDone: 'Todos los pasos están marcados como completados en este navegador.',
  remainingSteps: '{done} de {count} pasos están marcados como completados. Abre las otras pestañas para terminarlos.',
  progressReset: 'Tu progreso en este navegador se ha restablecido.',
  vendorScreenshotTag: 'CAPTURA DEL FABRICANTE',
  kombifyScreenshotTag: 'CAPTURA DE KOMBIFY',
  openVendorPage: 'Abrir la página del fabricante',
  openScreenshot: 'Abrir la captura',
  vendorImageUnavailable: 'Para cargarla se necesita conexión a internet.',
  imageUnavailable: 'La imagen no se ha cargado.',
  enlargeScreenshot: 'Ampliar captura: {description}',
  captured: 'capturada el {date}',
  vendorGuideTag: 'GUÍA DEL FABRICANTE',
  printGuide: 'Imprimir la guía',
  requirementsTitle: 'Lo que necesitas',
  officialApp: 'Oficial · {vendor}',
  thirdPartyApp: 'De terceros · {vendor}',
  setupSteps: 'Pasos de configuración',
  stepPosition: 'PASO {current} / {count}',
  progress: '{done} de {count} pasos completados',
  back: 'Atrás',
  finish: 'Terminar',
  next: 'Hecho · siguiente',
  imageSources: 'Fuentes de las imágenes y fecha',
  resetProgress: 'Restablecer progreso',
  sourcesTitle: 'Fuentes de las imágenes, enlaces comprobados y fecha',
  ownershipNotice: 'Guía de kombify · Los nombres de producto, las capturas de las apps de los fabricantes y las marcas pertenecen a sus respectivos propietarios.',
  vendorScreenshot: 'Captura del fabricante',
  screenshot: 'Captura',
  closeImage: 'Cerrar imagen',
  openOriginal: 'Abrir el original del fabricante',
  aboutScreenshot: 'Sobre esta captura',
};
