// German message catalog for ClientSetupGuide. Keys are stable message IDs and
// match snippets/client-setup-labels-en.jsx. Placeholders keep their names.
export const clientSetupLabelsDe = {
  appsTitle: 'Lade zuerst die App herunter.',
  stepsTitle: 'Verbinde dich Schritt für Schritt.',
  helpTitle: 'Du kommst nicht weiter?',
  nextTitle: 'Wie es weitergeht.',
  opensInNewTab: ' (öffnet in einem neuen Tab)',
  verifyRequired: 'Hake jeden Punkt ab, nachdem du ihn selbst geprüft hast.',
  allDone: 'Alle Schritte sind in diesem Browser als erledigt markiert.',
  remainingSteps: '{done} von {count} Schritten sind als erledigt markiert. Öffne die anderen Tabs, um sie abzuschließen.',
  progressReset: 'Dein Fortschritt in diesem Browser wurde zurückgesetzt.',
  vendorScreenshotTag: 'HERSTELLER-SCREENSHOT',
  kombifyScreenshotTag: 'KOMBIFY-SCREENSHOT',
  openVendorPage: 'Herstellerseite öffnen',
  openScreenshot: 'Screenshot öffnen',
  vendorImageUnavailable: 'Zum Laden ist eine Internetverbindung nötig.',
  imageUnavailable: 'Das Bild konnte nicht geladen werden.',
  enlargeScreenshot: 'Screenshot vergrößern: {description}',
  captured: 'aufgenommen am {date}',
  vendorGuideTag: 'HERSTELLER-ANLEITUNG',
  printGuide: 'Anleitung drucken',
  requirementsTitle: 'Was du brauchst',
  officialApp: 'Offiziell · {vendor}',
  thirdPartyApp: 'Drittanbieter · {vendor}',
  setupSteps: 'Einrichtungsschritte',
  stepPosition: 'SCHRITT {current} / {count}',
  progress: '{done} von {count} Schritten erledigt',
  back: 'Zurück',
  finish: 'Fertig',
  next: 'Erledigt · weiter',
  imageSources: 'Bildquellen und Datum',
  resetProgress: 'Fortschritt zurücksetzen',
  sourcesTitle: 'Bildquellen, geprüfte Links und Datum',
  ownershipNotice: 'Anleitung von kombify · Produktnamen, Screenshots von Hersteller-Apps und Marken gehören ihren jeweiligen Inhabern.',
  vendorScreenshot: 'Hersteller-Screenshot',
  screenshot: 'Screenshot',
  closeImage: 'Bild schließen',
  openOriginal: 'Original beim Hersteller öffnen',
  aboutScreenshot: 'Zu diesem Screenshot',
};
