// English source catalog for ClientSetupGuide. Keys are stable message IDs.
// Placeholders are plain text; preserve their names in translated catalogs.
export const clientSetupLabelsEn = {
  appsTitle: 'First, get the app.',
  stepsTitle: 'Connect step by step.',
  helpTitle: 'Stuck?',
  nextTitle: 'What comes next.',
  opensInNewTab: ' (opens in a new tab)',
  verifyRequired: 'Tick each point after you checked it yourself.',
  allDone: 'All steps are marked as done in this browser.',
  remainingSteps: '{done} of {count} steps are marked as done. Open the other tabs to finish them.',
  progressReset: 'Your progress in this browser was reset.',
  vendorScreenshotTag: 'VENDOR SCREENSHOT',
  kombifyScreenshotTag: 'KOMBIFY SCREENSHOT',
  openVendorPage: 'Open the vendor page',
  openScreenshot: 'Open the screenshot',
  vendorImageUnavailable: 'Loading it needs an internet connection.',
  imageUnavailable: 'The image did not load.',
  enlargeScreenshot: 'Enlarge screenshot: {description}',
  captured: 'captured {date}',
  vendorGuideTag: 'VENDOR GUIDE',
  printGuide: 'Print guide',
  requirementsTitle: 'What you need',
  officialApp: 'Official · {vendor}',
  thirdPartyApp: 'Third-party · {vendor}',
  setupSteps: 'Setup steps',
  stepPosition: 'STEP {current} / {count}',
  progress: '{done} of {count} steps done',
  back: 'Back',
  finish: 'Finish',
  next: 'Done · next',
  imageSources: 'Image sources and date',
  resetProgress: 'Reset progress',
  sourcesTitle: 'Image sources, checked links and date',
  ownershipNotice: 'Guide by kombify · Product names, screenshots of vendor apps and trademarks belong to their respective owners.',
  vendorScreenshot: 'Vendor screenshot',
  screenshot: 'Screenshot',
  closeImage: 'Close image',
  openOriginal: 'Open the original from the vendor',
  aboutScreenshot: 'About this screenshot',
};
