// Arabic message catalog for ClientSetupGuide. Keys are stable message IDs and
// match snippets/client-setup-labels-en.jsx. Placeholders keep their names.
export const clientSetupLabelsAr = {
  appsTitle: 'ابدأ بتنزيل التطبيق.',
  stepsTitle: 'اتصل خطوة بخطوة.',
  helpTitle: 'هل تحتاج إلى مساعدة؟',
  nextTitle: 'ما الخطوة التالية.',
  opensInNewTab: ' (يُفتح في علامة تبويب جديدة)',
  verifyRequired: 'ضع علامة على كل نقطة بعد أن تتحقق منها بنفسك.',
  allDone: 'جميع الخطوات مُعلَّمة كمكتملة في هذا المتصفح.',
  remainingSteps: '{done} من {count} خطوات مُعلَّمة كمكتملة. افتح علامات التبويب الأخرى لإكمالها.',
  progressReset: 'تمت إعادة ضبط تقدمك في هذا المتصفح.',
  vendorScreenshotTag: 'لقطة شاشة من المطوّر',
  kombifyScreenshotTag: 'لقطة شاشة من kombify',
  openVendorPage: 'افتح صفحة المطوّر',
  openScreenshot: 'افتح لقطة الشاشة',
  vendorImageUnavailable: 'يتطلب تحميلها اتصالاً بالإنترنت.',
  imageUnavailable: 'تعذّر تحميل الصورة.',
  enlargeScreenshot: 'تكبير لقطة الشاشة: {description}',
  captured: 'التُقطت في {date}',
  vendorGuideTag: 'دليل المطوّر',
  printGuide: 'اطبع الدليل',
  requirementsTitle: 'ما تحتاج إليه',
  officialApp: 'رسمي · {vendor}',
  thirdPartyApp: 'جهة خارجية · {vendor}',
  setupSteps: 'خطوات الإعداد',
  stepPosition: 'الخطوة {current} / {count}',
  progress: 'اكتملت {done} من {count} خطوات',
  back: 'رجوع',
  finish: 'إنهاء',
  next: 'تم · التالي',
  imageSources: 'مصادر الصور والتاريخ',
  resetProgress: 'إعادة ضبط التقدم',
  sourcesTitle: 'مصادر الصور والروابط التي جرى فحصها والتاريخ',
  ownershipNotice: 'دليل من kombify · أسماء المنتجات ولقطات شاشة تطبيقات المطوّرين والعلامات التجارية مملوكة لأصحابها.',
  vendorScreenshot: 'لقطة شاشة من المطوّر',
  screenshot: 'لقطة شاشة',
  closeImage: 'إغلاق الصورة',
  openOriginal: 'افتح الأصل من المطوّر',
  aboutScreenshot: 'حول لقطة الشاشة هذه',
};
