// Hindi message catalog for ClientSetupGuide. Keys are stable message IDs and
// match snippets/client-setup-labels-en.jsx. Placeholders keep their names.
export const clientSetupLabelsHi = {
  appsTitle: 'पहले ऐप डाउनलोड करें।',
  stepsTitle: 'चरण दर चरण कनेक्ट करें।',
  helpTitle: 'आगे नहीं बढ़ पा रहे?',
  nextTitle: 'आगे क्या करें।',
  opensInNewTab: ' (नए टैब में खुलता है)',
  verifyRequired: 'हर बिंदु को खुद जाँचने के बाद उस पर निशान लगाएँ।',
  allDone: 'सभी चरण इस ब्राउज़र में पूरे के रूप में चिह्नित हैं।',
  remainingSteps: '{count} में से {done} चरण पूरे के रूप में चिह्नित हैं। बाकी को पूरा करने के लिए दूसरे टैब खोलें।',
  progressReset: 'इस ब्राउज़र में आपकी प्रगति रीसेट हो गई है।',
  vendorScreenshotTag: 'विक्रेता का स्क्रीनशॉट',
  kombifyScreenshotTag: 'KOMBIFY स्क्रीनशॉट',
  openVendorPage: 'विक्रेता का पेज खोलें',
  openScreenshot: 'स्क्रीनशॉट खोलें',
  vendorImageUnavailable: 'इसे लोड करने के लिए इंटरनेट कनेक्शन चाहिए।',
  imageUnavailable: 'तस्वीर लोड नहीं हो सकी।',
  enlargeScreenshot: 'स्क्रीनशॉट बड़ा करें: {description}',
  captured: '{date} को लिया गया',
  vendorGuideTag: 'विक्रेता की गाइड',
  printGuide: 'गाइड प्रिंट करें',
  requirementsTitle: 'आपको क्या चाहिए',
  officialApp: 'आधिकारिक · {vendor}',
  thirdPartyApp: 'थर्ड-पार्टी · {vendor}',
  setupSteps: 'सेटअप के चरण',
  stepPosition: 'चरण {current} / {count}',
  progress: '{count} में से {done} चरण पूरे हुए',
  back: 'वापस',
  finish: 'पूरा करें',
  next: 'हो गया · आगे',
  imageSources: 'तस्वीरों के स्रोत और तारीख',
  resetProgress: 'प्रगति रीसेट करें',
  sourcesTitle: 'तस्वीरों के स्रोत, जाँचे गए लिंक और तारीख',
  ownershipNotice: 'kombify की गाइड · उत्पादों के नाम, विक्रेता ऐप के स्क्रीनशॉट और ट्रेडमार्क उनके संबंधित स्वामियों के हैं।',
  vendorScreenshot: 'विक्रेता का स्क्रीनशॉट',
  screenshot: 'स्क्रीनशॉट',
  closeImage: 'तस्वीर बंद करें',
  openOriginal: 'विक्रेता के यहाँ मूल तस्वीर खोलें',
  aboutScreenshot: 'इस स्क्रीनशॉट के बारे में',
};
