[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$requirements = @{
    "techstack/overview.mdx" = @(
        @{ Pattern = '(?i)\b(?:alpha|preview)\b'; Reason = "missing pre-1.0 availability label" }
    )
    "techstack/operating-modes.mdx" = @(
        @{ Pattern = '(?i)\bStackKits\b'; Reason = "missing StackKits execution boundary" }
    )
    "techstack/availability.mdx" = @(
        @{ Pattern = '(?i)\bWindows Alpha\b'; Reason = "missing released Windows Alpha status" }
    )
    "techstack/install-windows.mdx" = @(
        @{ Pattern = '(?i)https://github\.com/kombifyio/TechStack'; Reason = "missing official public source link" },
        @{ Pattern = '(?i)releases/latest/download/kombify-Techstack-Setup\.exe'; Reason = "missing official Windows Alpha asset" },
        @{ Pattern = '(?i)\bunsigned\b'; Reason = "missing unsigned-build warning" }
    )
}

$errors = [System.Collections.Generic.List[string]]::new()
foreach ($relativePath in $requirements.Keys) {
    $fullPath = Join-Path $repoRoot $relativePath
    if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) {
        $errors.Add("missing Techstack boundary page: $relativePath") | Out-Null
        continue
    }
    $content = Get-Content -LiteralPath $fullPath -Raw
    foreach ($requirement in $requirements[$relativePath]) {
        if ($content -notmatch $requirement.Pattern) {
            $errors.Add("$relativePath $($requirement.Reason)") | Out-Null
        }
    }
}

$techstackFiles = @(
    Get-ChildItem -LiteralPath (Join-Path $repoRoot "techstack") -File -Filter "*.mdx"
)

# The API and `techstack api` CLI reference exist only as the generated
# projection of one published Techstack release
# (scripts/render-api-surface-reference.mjs). Every file must carry that
# release and its source SHA, and nothing else may live under the reference.
$referenceRoot = Join-Path $repoRoot "techstack/reference"
$referenceRelease = "pending (no published Techstack release with api/surface yet)"
if (Test-Path -LiteralPath $referenceRoot) {
    $specRelative = "techstack/reference/api/openapi.yaml"
    $stamps = [System.Collections.Generic.HashSet[string]]::new()
    $referenceFiles = @(Get-ChildItem -LiteralPath $referenceRoot -Recurse -File)
    foreach ($file in $referenceFiles) {
        $relative = $file.FullName.Substring($repoRoot.Length).TrimStart("\", "/").Replace("\", "/")
        # Git checkouts may use CRLF on Windows; stamp syntax is line-ending neutral.
        $content = (Get-Content -LiteralPath $file.FullName -Raw).Replace("`r`n", "`n")
        if ($relative -eq $specRelative) {
            $header = [regex]::Match($content, '\A# Generated by render-api-surface-reference .*?\r?\n# Techstack (?<release>v\d+\.\d+\.\d+\S*) release \(source (?<sha>[0-9a-f]{40})\)')
            if (-not $header.Success) {
                $errors.Add("$relative is not the generated projection of a published release") | Out-Null
            }
            else {
                $stamps.Add("$($header.Groups['release'].Value) $($header.Groups['sha'].Value)") | Out-Null
            }
            if ($content -cmatch '(?m)^\s*(?:-\s+)?[''"]?x-kombify-[a-z-]+[''"]?\s*:') {
                $errors.Add("$relative carries x-kombify-* annotations") | Out-Null
            }
            if ($content -match '(?m)^ {2}[''"]?/\S*\binternal\b') {
                $errors.Add("$relative exposes an internal operation path") | Out-Null
            }
            continue
        }
        if ($relative -notmatch '^techstack/reference/cli/[a-z0-9-]+\.mdx$') {
            $errors.Add("$relative is not a generated Techstack reference file") | Out-Null
            continue
        }
        $release = [regex]::Match($content, '(?m)^release: "(?<value>v\d+\.\d+\.\d+\S*)"$')
        $source = [regex]::Match($content, '(?m)^source_hash: "(?<value>[0-9a-f]{40})"$')
        if ($content -notmatch '(?m)^generated_by: "render-api-surface-reference"$' -or -not $release.Success -or -not $source.Success) {
            $errors.Add("$relative lacks the generated release and source SHA stamp") | Out-Null
            continue
        }
        $stamps.Add("$($release.Groups['value'].Value) $($source.Groups['value'].Value)") | Out-Null
    }
    foreach ($required in @($specRelative, "techstack/reference/cli/overview.mdx")) {
        if (-not (Test-Path -LiteralPath (Join-Path $repoRoot $required) -PathType Leaf)) {
            $errors.Add("generated Techstack reference is incomplete: $required is missing") | Out-Null
        }
    }
    if ($stamps.Count -gt 1) {
        $errors.Add("generated Techstack reference mixes releases: $(@($stamps) -join ', ')") | Out-Null
    }
    elseif ($stamps.Count -eq 1) {
        $referenceRelease = @($stamps)[0]
    }
}

if ($errors.Count -gt 0) {
    Write-Host "Techstack public-boundary violations:"
    foreach ($errorMessage in $errors) {
        Write-Host " - $errorMessage"
    }
    throw "Techstack public-boundary validation failed"
}

Write-Host "techstack_public_release: windows-alpha"
Write-Host "techstack_public_boundary_files_checked: $($techstackFiles.Count)"
Write-Host "techstack_api_reference: $referenceRelease"
Write-Host "techstack_public_boundary: ok"
