name: Dependabot Safe Auto-Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  evaluate:
    uses: KombiverseLabs/.github/.github/workflows/dependabot-auto-merge.yml@d4da2c5e466639f614943675a4d2576b38f96a02
    permissions:
      contents: write
      pull-requests: write
