name: Mise Toolchain Update

on:
  schedule:
    - cron: '17 5 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: KombiverseLabs/.github/.github/workflows/mise-toolchain-update.yml@d4da2c5e466639f614943675a4d2576b38f96a02
    permissions:
      contents: read
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
